apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-stg
spec:
  project: demo-stg
  source:
    repoURL: https://github.com/damvinod/argocd-example.git
    path: guestbook
    targetRevision: main
    helm:
      valueFiles:
        - values-stg.yaml
      parameters:
        - name: replicaCount
          value: '2'
  destination:
    server: https://kubernetes.default.svc
    namespace: stg
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
