apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-for-app-set
spec:
  project: default
  source:
    repoURL: https://github.com/damvinod/argocd-example.git
    path: argocd-applicationset
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: false
      selfHeal: true