apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: application-set
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  project: default
  generators:
    - list:
        elements:
          - cluster: https://kubernetes.default.svc
            namespace: dev
            project: demo-dev
            name: visitorbook-app-set-dev
          - cluster: https://kubernetes.default.svc
            namespace: stg
            project: demo-stg
            name: visitorbook-app-set-stg
  template:
    metadata:
      name: '{{.name}}'
    spec:
      project: '{{.project}}'
      source:
        repoURL: https://github.com/damvinod/argocd-example.git
        targetRevision: main
        path: visitorbook
        helm:
          releaseName: '{{.name}}'
          valueFiles:
            - "values.yaml"
            - 'values-{{.namespace}}.yaml'
      destination:
        server: '{{.cluster}}'
        namespace: '{{.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true